// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDReDiZ3xM7NJxzi03UVxbW7HMg0fbpZSo',
    appId: '1:1075209502904:web:fb0b48d9a334d23434744d',
    messagingSenderId: '1075209502904',
    projectId: 'campus-claim',
    authDomain: 'campus-claim.firebaseapp.com',
    storageBucket: 'campus-claim.firebasestorage.app',
    measurementId: 'G-09YFN95YJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZoCvVtqaEaOgLpbxEQ4-RdokH5B1ueio',
    appId: '1:1075209502904:android:bd2bc3d37fad843634744d',
    messagingSenderId: '1075209502904',
    projectId: 'campus-claim',
    storageBucket: 'campus-claim.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOEQsY_bdCZm7ZuRaY76mxnII8zZvd0EQ',
    appId: '1:1075209502904:ios:ea2211aa63334ec234744d',
    messagingSenderId: '1075209502904',
    projectId: 'campus-claim',
    storageBucket: 'campus-claim.firebasestorage.app',
    iosBundleId: 'com.example.campusClaim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOEQsY_bdCZm7ZuRaY76mxnII8zZvd0EQ',
    appId: '1:1075209502904:ios:ea2211aa63334ec234744d',
    messagingSenderId: '1075209502904',
    projectId: 'campus-claim',
    storageBucket: 'campus-claim.firebasestorage.app',
    iosBundleId: 'com.example.campusClaim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDReDiZ3xM7NJxzi03UVxbW7HMg0fbpZSo',
    appId: '1:1075209502904:web:7f34c4fb3bb3f2ff34744d',
    messagingSenderId: '1075209502904',
    projectId: 'campus-claim',
    authDomain: 'campus-claim.firebaseapp.com',
    storageBucket: 'campus-claim.firebasestorage.app',
    measurementId: 'G-T7HK8G8FV1',
  );
}
